//types

export const FETCHING_USERS_REQUEST = 'FETCHING_USERS_REQUEST'
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS'
export const FETCHING_USERS_FAILURE = 'FETCHING_USERS_FAILURE'
export const SET_TIME = "SET_TIME"
export const GOT_TIME = "GOT_TIME"


export const GET_USER = 'GET_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const CREATE_USER = 'CREATE_USER'
