//types

export const FETCHING_USERS_REQUEST = 'FETCHING_USERS_REQUEST'
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS'
export const FETCHING_USERS_FAILURE = 'FETCHING_USERS_FAILURE'
export const SET_TIME = "SET_TIME"
export const GOT_TIME = "GOT_TIME"
export const SET_TIME_LEFT = "SET_TIME_LEFT"
export const START_TIMER = "START_TIMER"
export const TICK_TIMER = "TICK_TIMER"


export const GET_USER = 'GET_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const CREATE_USER = 'CREATE_USER'

export const GET_ALL_QUIZZES = 'GET_ALL_QUIZZES'
export const GET_ONE_QUIZ= 'GET_ONE_QUIZ'
export const UPDATE_QUIZ = 'UPDATE_QUIZ'

export const GET_ALL_ENTRIES = 'GET_ALL_ENTRIES'
export const GET_ONE_ENTRY = 'GET_ONE_ENTRY'
export const CREATE_ENTRY = 'CREATE_ENTRY'
export const DELETE_ENTRY = 'DELETE_ENTRY'
